FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD spring-boot-mybatis-druid.jar /opt/spring-boot-mybatis-druid/
EXPOSE 8080
WORKDIR /opt/spring-boot-mybatis-druid/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "spring-boot-mybatis-druid.jar"]
