#APIENV
APIENV: dev
#配置mysql
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    #Druid连接池配置
    initialSize: 1
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT NOW()
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties.druid.stat.mergeSql: true;
    connectionProperties.druid.stat.slowSqlMillis: 5000
#Mybatis
mybatis:
  #加载mybatis主要配置类
  config-location: classpath:mybatis/mybatis-config.xml
  #加载mapper配置类
  mapper-locations: classpath:mapper/*.xml
  #加载mapper实体类
  type-aliases-package: com.openopen.model

#Google Cloud SQL gcloud.sql.socketFactory
gcloud.sql.socketFactory: com.google.cloud.sql.postgres.SocketFactory
gcloud.sql.cloudSqlInstance: madou-goole-sheet-std-c19:asia-east1:my-tst-postgres-002




#Google Cloud Platform
google.cloud.platform.project.id: dev-my-project-28585


#Google Service Account
google.service.account.email: dirvetest123@dev-my-project-28585.iam.gserviceaccount.com
google.service.account.json.path: /dev-my-project-28585-67d6a87e811f.json


#Google Drive API
google.drive.folder.id: 18OfsWiCtFpCpjrIiAHo8MMpvJvGYMh7S
google.drive.teams.drive.id: 0AEnjMW6oO0e0Uk9PVA


# 最大上傳檔案大小
spring.servlet.multipart.max-file-size: 50MB
spring.servlet.multipart.max-request-size: 50MB
server.tomcat.max-swallow-size: -1



